#!/usr/bin/env python3
"""Generate card-images.ts from card_manifest.json.

Reads the manifest and produces a TypeScript mapping file:
  export const CARD_IMAGES: Record<string, string> = { ... }

Usage:
    python tools/gen_card_images.py
    python tools/gen_card_images.py --manifest path/to/card_manifest.json
    python tools/gen_card_images.py --dry-run  # Print to stdout instead
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
ENGINE_DIR = TOOLS_DIR.parent
RIG_DIR = ENGINE_DIR.parent
UI_DIR = RIG_DIR / "ed-ui"
OUTPUT_PATH = UI_DIR / "src" / "data" / "card-images.ts"
MANIFEST_PATH = TOOLS_DIR / "card_manifest.json"


def generate_ts(manifest: dict) -> str:
    """Generate TypeScript source from manifest."""
    lines = [
        "// Auto-generated by tools/gen_card_images.py — do not edit manually",
        "",
        "export const CARD_IMAGES: Record<string, string> = {",
    ]

    entries: list[tuple[str, str]] = []

    # Cards (critters + constructions)
    for card in manifest.get("cards", []):
        name = card.get("name", "")
        image_file = card.get("image_file", "")
        if name and image_file:
            entries.append((name, f"/assets/cards/{image_file}"))

    # Forest locations
    for loc in manifest.get("forest_locations", []):
        name = loc.get("name", "")
        image_file = loc.get("image_file", "")
        if name and image_file:
            entries.append((name, f"/assets/cards/{image_file}"))

    # Events
    for ev in manifest.get("events", []):
        name = ev.get("name", "")
        image_file = ev.get("image_file", "")
        if name and image_file:
            entries.append((name, f"/assets/cards/{image_file}"))

    # Sort alphabetically
    entries.sort(key=lambda e: e[0])

    for name, path in entries:
        # Escape any quotes in name
        safe_name = name.replace("'", "\\'")
        lines.append(f"  '{safe_name}': '{path}',")

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate card-images.ts from manifest")
    parser.add_argument("--manifest", default=str(MANIFEST_PATH), help="Path to card_manifest.json")
    parser.add_argument("--output", default=str(OUTPUT_PATH), help="Output TypeScript file path")
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout instead of writing")
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        print(f"ERROR: Manifest not found: {manifest_path}", file=sys.stderr)
        sys.exit(1)

    with open(manifest_path) as f:
        manifest = json.load(f)

    ts_content = generate_ts(manifest)

    total = (
        len(manifest.get("cards", []))
        + len(manifest.get("forest_locations", []))
        + len(manifest.get("events", []))
    )

    if args.dry_run:
        print(ts_content)
        print(f"\n// {total} card image entries", file=sys.stderr)
    else:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            f.write(ts_content)
        print(f"Written: {output_path} ({total} entries)")


if __name__ == "__main__":
    main()
